mode: ETH-XGaze
transform:
  face_size:
  - 224
  - 224
device: cuda
model:
  name: resnet50
bucketizer:
  num_bins: 720
  num_chunks: 2
  range:
  - -3.141592
  - 3.141592
face_detector:
  mode: face_alignment_sfd
  dlib:
    model: ./shape_predictor_68_face_landmarks.dat
gaze_estimator:
  checkpoint: ./last.pth.tar
  camera_params:
    image_width: 640
    image_height: 480
    camera_matrix:
      rows: 3
      cols: 3
      data:
      - 640
      - 0.0
      - 320
      - 0.0
      - 640
      - 240
      - 0.0
      - 0.0
      - 1.0
    distortion_coefficients:
      rows: 1
      cols: 5
      data:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
  normalized_camera_params:
    image_width: 224
    image_height: 224
    camera_matrix:
      rows: 3
      cols: 3
      data:
      - 960.0
      - 0.0
      - 112.0
      - 0.0
      - 960.0
      - 112.0
      - 0.0
      - 0.0
      - 1.0
    distortion_coefficients:
      rows: 1
      cols: 5
      data:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
  normalized_camera_distance: 0.6
demo:
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.05
  show_bbox: true
  show_head_pose: true
  show_landmarks: false
  show_template_model: false
cudnn:
  benchmark: true
  deterministic: false
