name: demo
channels:
- pytorch
dependencies:
- cmake
- numpy
- pip
- python=3.9
- pytorch::pytorch=1.10
- pytorch::torchvision
- pytorch::torchaudio
- pip:  
    - timm
    - scipy
    - omegaconf
    - opencv-contrib-python
    - dlib
    - face-alignment
    - mediapipe
    - gradio